@extends('layouts.app')

@section('content')
<!-- Page Content -->
    <div class="page-heading contact-heading header-text" style="background-image:url(../images/1.jpg)">
      <div class="container">
        <div class="row" style="margin-top: 42px;">
          <div class="col-md-12">
            <div class="text-content">
              <h4 class="heading">About Us</h4>
              
            </div>
          </div>
        </div>
      </div>
    </div>
   
    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2 class="sub-heading">About Irefill</h2>
            </div>
          </div>
          <div class="col-md-12">
            <div class="left-content texts">
      
              <p>Our motive is to reduce the impact on the environment caused by the plastic bottles. We are Introducing refilling technology, which will provide a platform to use packaging many times. It will reduce the dependency on the recycling. We want customers to pay only for the product not for the packaging. Irefill is an advanced contactless refilling technology for dispensing personal and home care products. This system is designed to bring an enormous change in environment. Customers can Opt  aluminium bottles, which can be reused by 50+ times and are 100% recyclable. We are partnering with brands and retailers to expand this technology.</p>
             <!--  <ul class="featured-list">
                <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                <li><a href="#">Consectetur an adipisicing elit</a></li>
                <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                <li><a href="#">Corporis, omnis doloremque</a></li>
                <li><a href="#">Non cum id reprehenderit</a></li>
              </ul> -->
              
            </div>
          </div>
         <!--  <div class="col-md-6">
            <div class="right-image">
              <img src="{{ asset('img/logo.png')}}" alt="">
            </div>
          </div> -->
        </div>
      </div>
    </div>


    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <div class="row">
                <div class="col-md-12">
          
                  <p>Irefill, an innovative step towards achieving sustainable lifestyle. Before plastic engulfs our planet, we with our unique idea focusing on zero waste management are here with new technology that will do wonders and bring a magnificent change in plastic waste management. According to facts, an average Indian uses about 11 shampoo bottles per year, now imagine if only 1 bottle would do the work of 11? Here is how you will play a major role as a safeguard to our environment. You reduce use of plastic at your home. By doing so, you contribute towards saving energy and cost required for recycling Most of all, you take an important step towards conserving our ecosystem, guarding the marine life and ensuring environmental sustainability.
Every year 300 million tonnes of waste is generated by humans, sadly only 9% of the total waste generated ends up being recycled and 8 million eventually ends up in oceans and rivers. Here we want folks to 'Pay for the product, not for packaging' Take a step towards eradicating plastic from our environment.
</p>
                </div>
              
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
 
@endsection
