

<?php $__env->startSection('content'); ?>
<!-- Page Content -->
    <div class="page-heading contact-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>Our Concept</h4>
              
            </div>
          </div>
        </div>
      </div>
    </div>
   
    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2> Irefill</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
      
              <p>Every year 300 million tonnes of waste is generated by humans, sadly only 9% of the total waste generated ends up being recycled and 8 million eventually ends up in oceans and rivers. Here we want folks to 'Pay for the product, not for packaging' Take a step towards eradicating plastic from our environment. </p>
             <!--  <ul class="featured-list">
                <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                <li><a href="#">Consectetur an adipisicing elit</a></li>
                <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                <li><a href="#">Corporis, omnis doloremque</a></li>
                <li><a href="#">Non cum id reprehenderit</a></li>
              </ul> -->
              
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              <img src="<?php echo e(asset('img/logo.png')); ?>" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>


<!--     <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <div class="row">
                <div class="col-md-8">
                  <h4>Creative &amp; Unique <em>Sixteen</em> Products</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque corporis amet elite author nulla.</p>
                </div>
                <div class="col-md-4">
                  <a href="#" class="filled-button">Purchase Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
 -->
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>